stages:
  data_ingestion:
    cmd: python src/nycTaxiProject.pipeline.stage_01_data_ingestion.py
    deps:
      - src/nycTaxiProject.pipeline.stage_01_data_ingestion
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/data.csv


